# env info
ox: osx
language: node_js
node_js: 12
cache:
  directories: node_modules

# install
install: npm install

# script
before_script: cd travel

script: npm run build

after_script: cd dist
  git init
  config user.name "mulili"
  config user.email "muli9611@gmail.com"
  git add .
  git commit -m "update pages"
  git push -f "https://${GIT_TOKEN}github.com/mulili/travel.git master:gh-pages"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
