# env info
os: osx
language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules

# install
install:
  - cd travel
  - npm install

# script
# before_script:

script:
  - cd travel
  - npm run build

after_script:
  - cd travel/dist
  - git init
  - git config user.name "mulili"
  - git config user.email "muli9611@gmail.com"
  - git remote add origin https://github.com/mulili/travel.git
  - git add .
  - git commit -m "update pages"
  - git push -f "https://${GIT_TOKEN}@github.com/mulili/travel.git" master:gh-pages

branches:
  only:
    - master
